name: Deploy to Firebase Hosting (Vite + React)

on:
  push:
    branches:
      - dev  # change to 'main' if you want to deploy from main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build with Vite
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master  # ✅ fixed version
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
